### ISSUE TITLE
Python Error on startup tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xaea1d3d8>)

### ISSUE THREAD

**Issue by notfixingit3** [OllisGit/OctoPrint-SpoolManager#200]
OS OctoPi: 0.18.0
OctoPrint: 1.6.1
Python 3.7.3
SpoolManager: 1.4.3

Octoprint on startup with all 3rd party plugins disabled except SpoolManager, all bundled plugins enabled, you get the following errors in octoprint.log

2021-09-16 23:03:32,318 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Databaseconnection with...
2021-09-16 23:03:32,318 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - {'useExternal': False, 'type': 'sqlite', 'host': 'localhost', 'port': 5432, 'name': 'SpoolDatabase', 'user': 'Olli', 'password': 'illO', 'baseFolder': '/home/pi/.octoprint/data/SpoolManager', 'fileLocation': '/home/pi/.octoprint/data/SpoolManager/spoolmanager.db'}
2021-09-16 23:03:32,320 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Database connection succesful. Checking Scheme versions
2021-09-16 23:03:32,321 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Databaseconnection with...
2021-09-16 23:03:32,322 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - {'useExternal': False, 'type': 'sqlite', 'host': 'localhost', 'port': 5432, 'name': 'SpoolDatabase', 'user': 'Olli', 'password': 'illO', 'baseFolder': '/home/pi/.octoprint/data/SpoolManager', 'fileLocation': '/home/pi/.octoprint/data/SpoolManager/spoolmanager.db'}
2021-09-16 23:03:32,323 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Database connection succesful. Checking Scheme versions
2021-09-16 23:03:32,324 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Databaseconnection with...
2021-09-16 23:03:32,326 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - {'useExternal': False, 'type': 'sqlite', 'host': 'localhost', 'port': 5432, 'name': 'SpoolDatabase', 'user': 'Olli', 'password': 'illO', 'baseFolder': '/home/pi/.octoprint/data/SpoolManager', 'fileLocation': '/home/pi/.octoprint/data/SpoolManager/spoolmanager.db'}
2021-09-16 23:03:32,328 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Database connection succesful. Checking Scheme versions
2021-09-16 23:03:32,339 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:10.1.6.30:
2021-09-16 23:03:32,342 - tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xaea1d3d8>)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/pi/oprint/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/sockjs/tornado/transports/rawwebsocket.py", line 90, in <lambda>
    self.server.io_loop.add_callback(lambda: self.send_pack(message, binary))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/sockjs/tornado/transports/rawwebsocket.py", line 85, in send_pack
    self.write_message(message, binary).add_done_callback(self.send_complete)
  File "/home/pi/oprint/lib/python3.7/site-packages/tornado/websocket.py", line 261, in write_message
    message = tornado.escape.json_encode(message)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/util/tornado.py", line 48, in fixed_json_encode
    return json.dumps(value, default=JsonEncoding.encode, allow_nan=False).replace(
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/json/__init__.py", line 49, in encode
    raise TypeError
TypeError

**Comment by OllisGit** [comment]
no feedback
